name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test -v

  test-iOS:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: rswift-dev
    - name: Put build into place
      run: |
        mkdir -p build/Debug
        mv rswift-dev/rswift build/Debug/rswift
        chmod +x build/Debug/rswift
    - name: Install pods
      run: pod install
    - name: Test
      run: fastlane scan --workspace "ResourceApp.xcworkspace" --scheme "ResourceApp"

  test-tvOS:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: rswift-dev
    - name: Put build into place
      run: |
        mkdir -p build/Debug
        mv rswift-dev/rswift build/Debug/rswift
        chmod +x build/Debug/rswift
    - name: Install pods
      run: pod install
    - name: Test
      run: fastlane scan --workspace "ResourceApp.xcworkspace" --scheme "ResourceApp-tvOS"

  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      run: |
        sed -i "" "s/\(static let version = \"\)Unknown\(\"\)/\1Development build: ${GITHUB_SHA}\2/" Sources/rswift/Rswift.swift
    - name: Build
      run: swift build -v -c release
    - name: Store artifact
      uses: actions/upload-artifact@v1
      with:
        name: rswift-dev
        path: .build/release/rswift
