name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: runalltests

  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      run: |
        sed -i "" "s/\(static let version = \"\)Unknown\(\"\)/\1Development build: ${GITHUB_SHA}\2/" Sources/rswift/Rswift.swift
    - name: Build
      run: swift build -v -c release
    - name: Store artifact
      uses: actions/upload-artifact@v1
      with:
        name: rswift-dev
        path: .build/release/rswift
